extends RefCounted

# (sem class_name — é consumido via preload em bestiario.gd, evitando depender
# do cache de classes globais)
#
# Dados estáticos do Bestiário (o "livro").
# Campos por inimigo: nome, mapa, categoria, icone, lore (descrição),
#   comportamento, fraqueza, avistamento (primeiro avistamento). Textos são
#   rascunhos — ajuste o tom à vontade.

const INIMIGOS: Array = [
	# ---------------- Mapa 1 — A Floresta ----------------
	{"nome": "Orc", "mapa": 1, "categoria": "Comum", "icone": "res://Icons/OrcPreview.png",
	 "lore": "Bruto verde de pouca conversa e muito porrete. Vem na frente do bando achando que tamanho é documento.",
	 "comportamento": "Avança em linha reta, na dianteira da horda.",
	 "fraqueza": "Corpo a corpo dos soldados.",
	 "avistamento": "Bosque inicial"},
	{"nome": "Abelha", "mapa": 1, "categoria": "Comum", "icone": "res://Icons/BeePreview.png",
	 "lore": "Pequena, rápida e furiosa — voa direto pra base ignorando o chão. O vovô jura que já levou uma ferroada dessas em 1968.",
	 "comportamento": "Voa em linha reta, ignorando o caminho.",
	 "fraqueza": "Defesas antiaéreas.",
	 "avistamento": "Bosque inicial"},
	{"nome": "Cogumelão", "mapa": 1, "categoria": "Comum", "icone": "res://Icons/MushroomPreview.png",
	 "lore": "Um cogumelo grande demais pra ser saudável. Anda devagar, mas aguenta pancada como ninguém.",
	 "comportamento": "Lento e resistente; serve de escudo aos outros.",
	 "fraqueza": "Dano contínuo de fogo.",
	 "avistamento": "Bosque inicial"},
	{"nome": "Golem de Musgo Ancestral", "mapa": 1, "categoria": "Chefe", "icone": "res://Icons/GolemBossPreview.png",
	 "lore": "Guardião milenar coberto de musgo. Acordou de mau humor e decidiu que a floresta inteira é só dele.",
	 "comportamento": "Marcha implacável e absorve muito dano.",
	 "fraqueza": "Fogo concentrado de várias torres.",
	 "avistamento": "Coração do bosque"},

	# ---------------- Mapa 2 — O Deserto Carmesim ----------------
	{"nome": "Chacal", "mapa": 2, "categoria": "Comum", "icone": "res://Icons/ChacalPreview.png",
	 "lore": "Ágil e faminto, corre em matilha pela areia quente. Onde aparece um, vêm mais cinco atrás.",
	 "comportamento": "Corre veloz e em grupo.",
	 "fraqueza": "Torres de área (morteiro).",
	 "avistamento": "Dunas escaldantes"},
	{"nome": "Anubis", "mapa": 2, "categoria": "Comum", "icone": "res://Icons/AnubisPreview.png",
	 "lore": "Servo de cabeça de chacal que protege os segredos do deserto. Leva a eternidade muito a sério.",
	 "comportamento": "Avança firme, protegendo os aliados.",
	 "fraqueza": "Perfuração do sniper.",
	 "avistamento": "Dunas escaldantes"},
	{"nome": "Genio", "mapa": 2, "categoria": "Comum", "icone": "res://Icons/GenioPreview.png",
	 "lore": "Saiu da lâmpada de mau humor e sem a menor vontade de realizar desejo nenhum.",
	 "comportamento": "Flutua e atrapalha as defesas.",
	 "fraqueza": "Gelo (lentidão).",
	 "avistamento": "Oásis perdido"},
	{"nome": "Servo do Deserto", "mapa": 2, "categoria": "Comum", "icone": "res://Icons/AnubisPreview.png",
	 "lore": "Capanga de areia que marcha em bando pelas dunas. Sozinho é fraco, em grupo é dor de cabeça.",
	 "comportamento": "Avança em grupo rumo à base.",
	 "fraqueza": "Dano em área.",
	 "avistamento": "Dunas do deserto"},
	{"nome": "Litch", "mapa": 2, "categoria": "Mini-Chefe", "icone": "res://Icons/LichPreview.png",
	 "lore": "Mago morto-vivo que troca a própria vida por feitiços. Custa a cair de vez.",
	 "comportamento": "Resiste e se recompõe sob pressão.",
	 "fraqueza": "Dano rápido e constante.",
	 "avistamento": "Tumba esquecida"},
	{"nome": "Faraó", "mapa": 2, "categoria": "Chefe", "icone": "res://Icons/FaraoPreview.png",
	 "lore": "O rei do deserto em pessoa. Comanda as areias e não perdoa quem invade sua tumba.",
	 "comportamento": "Comanda a horda e convoca reforços.",
	 "fraqueza": "Eliminar os reforços primeiro.",
	 "avistamento": "Câmara do sarcófago"},

	# ---------------- Mapa 3 — A Casa da Bruxa ----------------
	{"nome": "Abóbora", "mapa": 3, "categoria": "Comum", "icone": "res://Icons/AboboraPreview.png",
	 "lore": "Lanterna sorridente que rola sem dó em direção à base. Doçura? Só travessura.",
	 "comportamento": "Rola ganhando velocidade até a base.",
	 "fraqueza": "Lentidão para frear cedo.",
	 "avistamento": "Vila assombrada"},
	{"nome": "Bilbo", "mapa": 3, "categoria": "Comum", "icone": "res://Icons/FrankPreview.png",
	 "lore": "Criatura remendada e desengonçada. Forte, lenta e com um parafuso a menos (literalmente).",
	 "comportamento": "Lento, porém muito pancudo.",
	 "fraqueza": "Fogo e dano em área.",
	 "avistamento": "Laboratório nos fundos"},
	{"nome": "Cavaleiro", "mapa": 3, "categoria": "Mini-Chefe", "icone": "res://Icons/CavaleiroPreview.png",
	 "lore": "Armadura assombrada que não larga a espada nem depois de morto.",
	 "comportamento": "Investe e aguenta muitos golpes.",
	 "fraqueza": "Perfuração pesada.",
	 "avistamento": "Salão dos retratos"},
	{"nome": "Aprendiz da Bruxa", "mapa": 3, "categoria": "Comum", "icone": "res://Icons/AprendizBruxaPreview.png",
	 "lore": "Bruxinho atrapalhado invocado pela patroa. Vem em bando quando ela cacareja.",
	 "comportamento": "Surge das invocações da Bruxa e avança em grupo.",
	 "fraqueza": "Dano em área enquanto estão amontoados.",
	 "avistamento": "Sótão da bruxa"},
	{"nome": "Bruxa", "mapa": 3, "categoria": "Chefe", "icone": "res://Icons/BruxaPreview.png",
	 "lore": "A dona da casa. Invoca capangas e solta feitiços enquanto cacareja de prazer.",
	 "comportamento": "Invoca capangas e ataca à distância.",
	 "fraqueza": "Pressão rápida antes das invocações.",
	 "avistamento": "Sótão da bruxa"},

	# ---------------- Mapa 4 — A Fenda dos Piratas ----------------
	{"nome": "Monstro Peixe", "mapa": 4, "categoria": "Comum", "icone": "res://Icons/PeixePreview.png",
	 "lore": "Peixe grande e mal-encarado que saiu da água só pra arrumar encrenca.",
	 "comportamento": "Avança em cardume pela orla.",
	 "fraqueza": "Torres de área.",
	 "avistamento": "Mar aberto"},
	{"nome": "Bombardeiro", "mapa": 4, "categoria": "Comum", "icone": "res://Icons/BombardeiroPreview.png",
	 "lore": "Pirata aéreo que sobrevoa as defesas largando explosivos. Mira na base, não no chão.",
	 "comportamento": "Sobrevoa as defesas bombardeando.",
	 "fraqueza": "Defesas antiaéreas.",
	 "avistamento": "Céus da enseada"},
	{"nome": "Tutuba", "mapa": 4, "categoria": "Mini-Chefe", "icone": "res://Icons/TubaraoPreview.png",
	 "lore": "Tubarão faminto com dentes pra dois. Avança rápido e não dá ré.",
	 "comportamento": "Arranca veloz, sem recuar.",
	 "fraqueza": "Lentidão (gelo).",
	 "avistamento": "Águas profundas"},
	{"nome": "Holandês Voador", "mapa": 4, "categoria": "Chefe", "icone": "res://Icons/HolandesPreview.png",
	 "lore": "O navio amaldiçoado e seu capitão fantasma. Arrasta uma tripulação inteira de assombrações.",
	 "comportamento": "Arrasta tripulação fantasma e tanka muito.",
	 "fraqueza": "Foco no casco principal.",
	 "avistamento": "Névoa da fenda"},

	# ---------------- Mapa 5 — O Planeta Maluco ----------------
	{"nome": "Alexa astronauta", "mapa": 5, "categoria": "Comum", "icone": "res://Icons/AlexaPreview.png",
	 "lore": "Assistente de bordo que ganhou vontade própria — e um traje espacial de brinde.",
	 "comportamento": "Patrulha metódica rumo à base.",
	 "fraqueza": "Dano elétrico.",
	 "avistamento": "Órbita distante"},
	{"nome": "Linigena astronauta", "mapa": 5, "categoria": "Comum", "icone": "res://Icons/AlienPreview.png",
	 "lore": "Alienígena curioso de fato espacial. Veio de muito longe só pra atrapalhar.",
	 "comportamento": "Avança em zigue-zague, desviando.",
	 "fraqueza": "Torres de área.",
	 "avistamento": "Órbita distante"},
	{"nome": "Sapao Astronauta", "mapa": 5, "categoria": "Comum", "icone": "res://Icons/SapoPreview.png",
	 "lore": "Anfíbio gigante em órbita. Pula obstáculos como se a gravidade fosse opcional.",
	 "comportamento": "Salta sobre obstáculos e defesas.",
	 "fraqueza": "Gelo (lentidão).",
	 "avistamento": "Crateras lunares"},
	{"nome": "Fernando o flamingo", "mapa": 5, "categoria": "Comum", "icone": "res://Icons/FlamingoPreview.png",
	 "lore": "Flamingo cósmico de elegância duvidosa. Voa torto, mas sempre chega.",
	 "comportamento": "Voo irregular rumo à base.",
	 "fraqueza": "Defesas antiaéreas.",
	 "avistamento": "Anéis do planeta"},
	{"nome": "Tentáculo Cósmico", "mapa": 5, "categoria": "Comum", "icone": "res://Icons/TentaculoPreview.png",
	 "lore": "Apêndice cósmico que se arrasta sozinho rumo à base. Nojento e teimoso.",
	 "comportamento": "Pequeno e teimoso; fura a fila.",
	 "fraqueza": "Tiro rápido.",
	 "avistamento": "Superfície vermelha"},
	{"nome": "Cosmic Kraken", "mapa": 5, "categoria": "Chefe", "icone": "res://Icons/KrakenPreview.png",
	 "lore": "Horror tentacular vindo do vazio entre as estrelas. Encara você com olhos demais.",
	 "comportamento": "Esmaga defesas com os tentáculos.",
	 "fraqueza": "Dano massivo concentrado.",
	 "avistamento": "Vazio entre estrelas"},

	# ---------------- Mapa 6 — O Covil do Dragão ----------------
	{"nome": "Demoniozinho", "mapa": 6, "categoria": "Comum", "icone": "res://Icons/DemoniozinhoPreview.png",
	 "lore": "Capeta de bolso que voa direto pra base soltando fumacinha. Pequeno, mas atrevido.",
	 "comportamento": "Voa em linha reta, ignorando o chão.",
	 "fraqueza": "Defesas antiaéreas.",
	 "avistamento": "Portões do covil"},
	{"nome": "Lava golem", "mapa": 6, "categoria": "Mini-Chefe", "icone": "res://Icons/FireGolemPreview.png",
	 "lore": "Mole de rocha derretida. Cada passo deixa o chão fumegando atrás de si.",
	 "comportamento": "Pisa forte, deixando rastro de brasa.",
	 "fraqueza": "Gelo (lentidão).",
	 "avistamento": "Rios de lava"},
	{"nome": "Dragao Inicial", "mapa": 6, "categoria": "Comum", "icone": "res://Icons/DragaoBebePreview.png",
	 "lore": "Filhote de dragão cuspindo as primeiras fagulhas. Fofo até a hora de abrir a boca.",
	 "comportamento": "Anda e solta fagulhas curtas.",
	 "fraqueza": "Tiro rápido.",
	 "avistamento": "Ninho de pedra"},
	{"nome": "Dragao Evoluido", "mapa": 6, "categoria": "Mini-Chefe", "icone": "res://Icons/DragaoJovemPreview.png",
	 "lore": "Já cresceu, já voa e já queima. A adolescência dele é movida a fogo.",
	 "comportamento": "Voa e queima as defesas de longe.",
	 "fraqueza": "Defesas antiaéreas.",
	 "avistamento": "Penhascos do covil"},
	{"nome": "Dragao Final", "mapa": 6, "categoria": "Chefe", "icone": "res://Icons/DragaoAdultoPreview.png",
	 "lore": "O senhor do covil em sua forma plena. A batalha final pelos netos.",
	 "comportamento": "Domina o ar e o chão; cospe fogo intenso.",
	 "fraqueza": "Tudo o que você tiver — é a luta final.",
	 "avistamento": "Trono de magma"},
]

const MAPAS: Array = [
	{"numero": 1, "nome": "A Floresta",         "thumb": "res://Icons/Map1Selcetor.png",
	 "cutscene": "res://Cenas Locais/Cutscenes/cutscene_dinamica.tscn"},
	{"numero": 2, "nome": "O Deserto Carmesim",  "thumb": "res://Icons/Map2Selector.png",
	 "cutscene": "res://Cenas Locais/Cutscenes/cutscene_animada_2.tscn"},
	{"numero": 3, "nome": "A Casa da Bruxa",     "thumb": "res://Icons/Map3Selector.png",
	 "cutscene": "res://Cenas Locais/Cutscenes/cutscene_animada_3.tscn"},
	{"numero": 4, "nome": "A Fenda dos Piratas", "thumb": "res://Icons/Map4Selector.png",
	 "cutscene": "res://Cenas Locais/Cutscenes/cutscene_animada_4.tscn"},
	{"numero": 5, "nome": "O Planeta Maluco",    "thumb": "res://Icons/Map5Selector.png",
	 "cutscene": "res://Cenas Locais/Cutscenes/cutscene_animada_5.tscn"},
	{"numero": 6, "nome": "O Covil do Dragão",   "thumb": "res://Icons/Map6Selector.png",
	 "cutscene": "res://Cenas Locais/Cutscenes/cutscene_animada_6.tscn"},
]

const NOMES_MAPAS: Array = ["", "A Floresta", "O Deserto Carmesim", "A Casa da Bruxa",
	"A Fenda dos Piratas", "O Planeta Maluco", "O Covil do Dragão"]

# Catálogo de construções do bestiário. "id" precisa bater com o que é registrado
# em Global.construcoes_descobertas (build_slot.gd e Builds.gd). "tipo" define a cor
# da borda: "ofensiva" (vermelho), "economia" (dourado), "defesa" (azul).
const CONSTRUCOES: Array = [
	{"id": "torre", "nome": "Torre", "tipo": "ofensiva",
	 "icone": "res://Assets/Construcoes/ConstrucaoTorre.png",
	 "descricao": "Atira flechas nos inimigos que passam por perto. A defesa mais básica e confiável.",
	 "melhoria": "Pode evoluir para Morteiro, Sniper, Torre de Fogo ou Tesla."},
	{"id": "quartel", "nome": "Quartel", "tipo": "defesa",
	 "icone": "res://Assets/Construcoes/ConstrucaoQuartel.png",
	 "descricao": "Solta soldados que enfrentam os inimigos no chão e renascem ao morrer.",
	 "melhoria": "Guarda Real: solta espadachins de corpo a corpo."},
	{"id": "mina", "nome": "Mina", "tipo": "economia",
	 "icone": "res://Assets/Construcoes/ConstrucaoMina.png",
	 "descricao": "Produz ouro extra ao fim de cada onda.",
	 "melhoria": "Rende ainda mais ouro a cada melhoria."},
	{"id": "casa", "nome": "Casa", "tipo": "economia",
	 "icone": "res://Assets/Construcoes/ConstrucaoCasa.png",
	 "descricao": "Gera ouro passivo para a sua aldeia.",
	 "melhoria": "Aumenta a renda gerada por onda."},
	{"id": "moinho", "nome": "Moinho", "tipo": "economia",
	 "icone": "res://Assets/Construcoes/ConstrucaoMoinho.png",
	 "descricao": "Processa recursos e rende ouro a cada onda.",
	 "melhoria": "Processa mais recursos por melhoria."},
	{"id": "mercadinho", "nome": "Mercadinho Egípcio", "tipo": "economia",
	 "icone": "res://Assets/Construcoes/ConstrucaoDeserto.png",
	 "descricao": "Mercado exclusivo do Deserto Carmesim. Rende ouro a cada onda.",
	 "melhoria": "Rende mais ouro a cada melhoria."},
	{"id": "taverna", "nome": "Taverna dos Piratas", "tipo": "economia",
	 "icone": "res://Assets/Construcoes/ConstrucaoPirata.png",
	 "descricao": "Taverna exclusiva da Fenda dos Piratas. Rende ouro a cada onda.",
	 "melhoria": "Rende mais ouro a cada melhoria."},
	{"id": "caldeirao", "nome": "Caldeirão", "tipo": "ofensiva",
	 "icone": "res://Assets/Construcoes/ConstrucaoBruxa.png",
	 "descricao": "Lança poções que causam dano em área e envenenam os inimigos.",
	 "melhoria": "Explosões maiores e mais veneno."},
	{"id": "morteiro", "nome": "Morteiro", "tipo": "ofensiva",
	 "icone": "res://Assets/Construcoes/ConstrucaoTorre2A.png",
	 "descricao": "Evolução da Torre. Dispara bombas que explodem em área.",
	 "melhoria": "Mais dano e cadência reduzida."},
	{"id": "sniper", "nome": "Sniper", "tipo": "ofensiva",
	 "icone": "res://Assets/Construcoes/ConstrucaoTorre2B.png",
	 "descricao": "Evolução da Torre. Acerta inimigos de muito longe com tiros certeiros.",
	 "melhoria": "Maior alcance a cada melhoria."},
	{"id": "torre_fogo", "nome": "Torre de Fogo", "tipo": "ofensiva",
	 "icone": "res://Assets/Construcoes/ConstrucaoCovil.png",
	 "descricao": "Evolução da Torre (Covil do Dragão). Queima vários inimigos ao mesmo tempo.",
	 "melhoria": "O dano cresce quanto mais tempo no alvo."},
	{"id": "tesla", "nome": "Tesla", "tipo": "ofensiva",
	 "icone": "res://Assets/Construcoes/ConstrucaoScifi.png",
	 "descricao": "Evolução da Torre (Planeta Maluco). Solta raios que saltam entre os inimigos.",
	 "melhoria": "Dano em cadeia mais forte."},
]

# Extrai com segurança as imagens (quadros) da cutscene de uma fase, SEM rodar a
# cutscene: instantiate() não dispara _ready, então lemos o export e liberamos.
static func obter_imagens_historia(caminho_cutscene: String) -> Array:
	var imgs: Array = []
	if caminho_cutscene == "" or not ResourceLoader.exists(caminho_cutscene):
		return imgs
	var cena := load(caminho_cutscene)
	if cena == null:
		return imgs
	var inst = cena.instantiate()
	if inst != null:
		if "imagens" in inst and inst.imagens != null:
			for t in inst.imagens:
				if t != null:
					imgs.append(t)
		inst.free()
	return imgs
